AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stock Data Pipeline

Parameters:
  AlphaVantageApiKey:
    Type: String
    NoEcho: true
    Description: API Key for Alpha Vantage
  BucketName:
    Type: String
    Default: stock-quotes-data
    Description: S3 bucket name for stock data

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    MemorySize: 128
    Environment:
      Variables:
        ALPHA_VANTAGE_API_KEY: !Ref AlphaVantageApiKey
        BUCKET_NAME: !Ref BucketName

Resources:
  StockDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldData
            Status: Enabled
            ExpirationInDays: 365

  StockFetcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 18 ? * MON-FRI *)
            Name: daily-stock-fetch
            Description: Fetch stock data every weekday at 3PM UTC (10AM EST)

Outputs:
  StockDataBucketName:
    Description: Name of the S3 bucket for stock data
    Value: !Ref StockDataBucket
  StockFetcherFunctionName:
    Description: Name of the Lambda function
    Value: !Ref StockFetcherFunction
